# Generated by Django 4.2.30 on 2026-06-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
