# Generated by Django 4.2.30 on 2026-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_branch_user_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("SUB_ADMIN", "Branch Administrator"),
                    ("DOCTOR", "Doctor"),
                    ("RECEPTIONIST", "Receptionist"),
                    ("PHARMACIST", "Pharmacist"),
                    ("LAB_TECH", "Lab Technician"),
                    ("PATIENT", "Patient"),
                ],
                default="PATIENT",
                max_length=20,
            ),
        ),
    ]
