# Generated by Django 4.2.30 on 2026-06-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_branch_email_branch_manager_branch_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_name", models.CharField(default="MediFlow", max_length=200)),
                ("tagline", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_logos/"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("invoice_prefix", models.CharField(default="HMS-INV", max_length=20)),
                ("currency_symbol", models.CharField(default="Rs.", max_length=10)),
                (
                    "doctor_fee_share",
                    models.DecimalField(decimal_places=2, default=80, max_digits=5),
                ),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("reminder_hours", models.IntegerField(default=24)),
                ("opd_start_time", models.TimeField(default="09:00:00")),
                ("opd_end_time", models.TimeField(default="17:00:00")),
                ("off_days", models.CharField(default="Sunday", max_length=100)),
                ("max_slots_per_hour", models.IntegerField(default=4)),
            ],
        ),
    ]
