# Generated by Django 4.2.30 on 2026-06-08 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0003_branch_user_branch"),
        ("patients", "0002_patient_branch"),
        ("clinical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="authentication.branch",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="icd_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="icd_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PatientVitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_pressure",
                    models.CharField(help_text="e.g. 120/80", max_length=20),
                ),
                ("pulse", models.PositiveIntegerField(help_text="bpm")),
                (
                    "temperature",
                    models.DecimalField(decimal_places=1, help_text="F", max_digits=4),
                ),
                ("oxygen_saturation", models.PositiveIntegerField(help_text="%")),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, help_text="kg", max_digits=5),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, help_text="cm", max_digits=5),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
