# Generated by Django 4.2.30 on 2026-06-09 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_supplier_medicine_branch_medicine_reorder_level_and_more"),
        ("clinical", "0002_appointment_branch_prescription_icd_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription_items",
                to="pharmacy.medicine",
            ),
        ),
    ]
