# Generated by Django 4.2.30 on 2026-06-06 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("bed_number", models.CharField(max_length=30, unique=True)),
                ("is_occupied", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "ward_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Ward"),
                            ("ICU", "Intensive Care Unit"),
                            ("PRIVATE", "Private Room"),
                            ("CCU", "Cardiac Care Unit"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("total_beds", models.PositiveIntegerField()),
                ("cost_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BedAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admission_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("discharge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ADMITTED", "Admitted"),
                            ("DISCHARGED", "Discharged"),
                        ],
                        default="ADMITTED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "admitting_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="staff.doctor",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="ipd.bed",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bed",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="ipd.ward",
            ),
        ),
    ]
