# Generated by Django 4.2.30 on 2026-06-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipd", "0002_otroom_otbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="bed_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Bed"),
                    ("ICU", "ICU Bed"),
                    ("PRIVATE", "Private Bed"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bed",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("OCCUPIED", "Occupied"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="floor_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ward",
            name="ward_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Ward"),
                    ("ICU", "Intensive Care Unit"),
                    ("PRIVATE", "Private Room"),
                    ("CCU", "Cardiac Care Unit"),
                    ("MATERNITY", "Maternity Ward"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
