# Generated by Django 4.2.30 on 2026-06-09 00:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="base_salary",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("120000.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="base_salary",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
