# Generated by Django 4.2.30 on 2026-06-09 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_doctor_base_salary_staffprofile_base_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="join_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="base_salary",
            field=models.DecimalField(decimal_places=2, default=40000.0, max_digits=10),
        ),
    ]
