# Generated by Django 4.2.30 on 2026-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_staffprofile_employee_id_staffprofile_join_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="doctor_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Physician"),
                    ("CARDIOLOGIST", "Cardiologist"),
                    ("NEUROLOGIST", "Neurologist"),
                    ("ORTHOPEDIC", "Orthopedic Surgeon"),
                    ("PEDIATRICIAN", "Pediatrician"),
                    ("GYNECOLOGIST", "Gynecologist"),
                    ("DERMATOLOGIST", "Dermatologist"),
                    ("ENT", "ENT Specialist"),
                    ("OPHTHALMOLOGIST", "Ophthalmologist"),
                    ("UROLOGIST", "Urologist"),
                    ("PSYCHIATRIST", "Psychiatrist"),
                    ("PULMONOLOGIST", "Pulmonologist"),
                    ("GASTROENTEROLOGIST", "Gastroenterologist"),
                    ("NEPHROLOGIST", "Nephrologist"),
                    ("ONCOLOGIST", "Oncologist"),
                    ("ENDOCRINOLOGIST", "Endocrinologist"),
                    ("RHEUMATOLOGIST", "Rheumatologist"),
                    ("SURGEON", "General Surgeon"),
                    ("ANESTHETIST", "Anesthetist"),
                    ("RADIOLOGIST", "Radiologist"),
                    ("PATHOLOGIST", "Pathologist"),
                    ("DENTIST", "Dentist"),
                    ("PHYSIOTHERAPIST", "Physiotherapist"),
                    ("OTHER", "Other"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
    ]
